### ISSUE TITLE
stoped working

### ISSUE THREAD

**Issue by abdullaha6a** [thatmarcel/crunchyrold#2]
stoped working after last crunchyroll update

**Comment by thatmarcel** [comment]
Sorry for the long delay :/

They changed a few things behind the scenes regarding sign-in and streaming so even with newer credentials, the app didn't work anymore. I've updated the tweak to make the app use the newer endpoints where needed, so you should be able to use the app again by using [v1.1.0](https://github.com/thatmarcel/crunchyrold/releases/tag/1.1.0) of the tweak.
