### ISSUE TITLE
Can you update it

### ISSUE THREAD

**Issue by AnCry1596** [thatmarcel/crunchyrold#3]
I see Crunchyroll lastest APK in apkpure have this downloadlink: https://d.apkpure.com/b/APK/com.crunchyroll.crunchyroid?version=latest

Can you update it?

**Comment by thatmarcel** [comment]
Sorry for the long delay :/

They changed a few things behind the scenes regarding sign-in and streaming so even with newer credentials, the app didn't work anymore. I've updated the tweak to make the app use the newer endpoints where needed, so you should be able to use the app again by using [v1.1.0](https://github.com/thatmarcel/crunchyrold/releases/tag/1.1.0) of the tweak.
